#include <iostream>
#include "../Token.cpp"

using namespace std;

//states
TokenType const *TokenTypeTableX = {
    LETTER,
    DIGIT,
    PRINTABLE,
    MULTIPLICATIVE_OP,
    ADDITIVE_OP,
    RELATIONAL_OP,
    LEFT_BRACKET,
    RIGHT_BRACKET,
    COLON,
    SEMI_COLON,
    PERIOD,
    COMMA,
    EQUALS,
    UNDERSCORE,
    EXCLAMATION_MARK,
    INVERTED_COMMA,
    TOK_EOF,
    TYPE,
    BOOLEAN_LITERAL,
    INTEGER_LITERAL,
    REAL_LITERAL,
    STRING_LITERAL,
    LITERAL,
    IDENTIFIER,

    //transition table conmments start here
    SUB_EXPRESSION,
    UNARY,
    FACTOR,
    TERM,
    SIMPLE_EXPRESSION,
    EXPRESSION,
    ASSIGNMENT,
    VARIABLE_DECL,
    PRINT_STATEMENT,
    RETURN_STATEMENT,
    IF_STATEMENT,
    WHILE_STATEMENT,
    FORMAL_PARAM,
    FORMAL_PARAMS,
    FUNCTION_DECL,
    STATEMENT,
    BLOCK,
    PROGRAM};

//final states
TokenType const *finalStates = {
    LETTER,
    NULL,
    NULL,
    NULL,
    NULL,
    RELATIONAL_OP,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    INTEGER_LITERAL,
    REAL_LITERAL,
    STRING_LITERAL,
    LITERAL,
    IDENTIFIER,
}